version: '3.3'
services:
  db:
    image: arangodb
    restart: always
    environment:
      ARANGO_ROOT_PASSWORD: 1
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '8529:8529'
    expose:
      # Opens port 3306 on the container
      - '8529'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/arangodb3
# Names our volume
volumes:
  my-db: